[Settings]
ServerName=BUL_SPRO25000
DatabaseName=STORESQL
SQLDriver=SQL Server
StoreNumber=3
FTPServerIP=10.0.130.18
LogPurge=1
ReportPurge=30

[ImportOrders]
BaseUrl=https://plm-uat-larry.invafresh.com/v1
Username=wsuser
Password=plmwsuser123


[Maceri]
MaceriLocationID=PLMORC
Username=app1@tommaceritest.com
Password=Test#123
FbReferer=https://tommaceri-test.fbportal.io
BaseUrlAuth=https://freshapi.freshbyte.tech/api/v1/auth/login
BaseUrlOrder=https://freshapi.freshbyte.tech/api/v1/erp/onlineorders?dropinvaliditems=True


[Lipari]
LipariLocationID=3

[Lipari_Departments]
10=12557005
11=12557011
12=12557004
20=12557074
30=12557007
32=12557031
40=12557006
70=12557001
80=12557002

[UNFI]
;AuthUrl=https://password-auth.geniuscentral.com/
;ApiBaseUrl=https://posapi.geniuscentral.com
AuthUrl=https://password-auth.geniuscentral.com/
ApiBaseUrl=https://posapi.dev.geniuscentral.com
ApiStoreChainId=142139
Username=plummarketorderlink
Password="(c6^7YK9}'gj"
ClientId=4f6ln05ghnf68ls93vu8eqsuee
TimeoutAuthSec=90
TimeoutPostSec=120

[UNFIGW]
SupplierId=3954
SupplierName=UNFI Greenwood
AccountNumber=88454
StoreID=127705

[UNFIRC]
SupplierId=7313
SupplierName=UNFI Racine
AccountNumber=96621
StoreID=127705
