@WIZRPL(TMPFILE=TMP_@STORE@TER@FMT(R3,@dbHot(regGen,TMPDB,1,1000)));
@WIZRPL(STYLE=TXT);
@WIZRPL(OUTPUT=XF@dbHot(REDIRMAIL)\@WIZGET(TMPFILE).sql);

@EXEC(CGI=Ravyx_send_email_rec);

@WIZCLR(STYLE);
@WIZCLR(OUTPUT);

